# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c98781ad6691669b59196e50aa06eba67b74da7a49c74d8a0c47f2d380058b3d6960783915a38c695837da71a042df1f858089e6b24c4bb39d550e5014a87c5

test:
  secret_key_base: b37822647cdedb61745c0ac506906aefadff1ddef7cdb272c8a19bba91f077bd6e1da6277908ab0c6037745b79fefc84624bb1637a219655336c728fdccbff65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
